apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}
  namespace: {{.Values.app.namespace}}
spec:
  selector:
    app: {{.Chart.Name}}
  type: ClusterIP
  ports:
    - port: {{.Values.app.port}}
      targetPort: {{.Values.app.port}}
